### ISSUE TITLE
GetMeshSection returns individual triangles?

### ISSUE THREAD

**Issue by rehven** [Koderz/UE4RuntimeMeshComponent#27]
I create an RMC using CopyRuntimeMeshFromStaticMeshComponent, with a simple cube (8 verts)
`URuntimeMeshLibrary::CopyRuntimeMeshFromStaticMeshComponent(smc, 0, rmc, false);`

Then I extract Vertices and Indices from the RMC:
`const IRuntimeMeshVerticesBuilder* Vertices = nullptr;`
`const FRuntimeMeshIndicesBuilder* Indices = nullptr;`
`rmc->GetSectionMesh(0, Vertices, Indices);`

Now I have 24 indices instead of the expected 8. 

1. Why would my original static mesh be divided into totally separate triangles that don't share vertices?
2. Is the CopyRuntimeMesh... function splitting the original staticmesh into separate triangles, or is it the GetSectionMesh function?
3. Am I ok merging vertices back together and resubmitting it to RMC?

**Comment by rehven** [comment]
My mistake, that should be "Now I have 24 VERTICES..."

**Comment by Zinglish** [comment]
First off, RMC doesn't abstract away from meshes and raw triangle data, you will have to write your own wrapper for returning and managing grouped verts / quads. Secondly RMC meshes **definitely do** share verts amongst triangles you just haven't explored further. RMC merely abstracts away from mesh vertice updates.

You should go through [Mesh Basics](https://github.com/Koderz/UE4RuntimeMeshComponent/wiki/Mesh-Basics) in the Wiki to understand that triangles do have shared verts, the structure that represents them is most likely a bit different to what you're used to.

Not to be a dick or anything but next time read the documentation / wiki before asking questions, you will save yourself and the developer so much time.

**Comment by Koderz** [comment]
Hey @rehven 

Just to clear up the specific of why you have 24 vertices now. Each of the 6 sides has it's own 4 vertices. The reason is so that things like normal/tangent/uv can be different for each side, otherwise you'd have a cube that looked sort of like a sphere due to smooth lighting across the edges. It's still sharing as much of the vertices as possible as if you went by straight triangles it would take 36, 3 for each of the 2 triangles for each of the 6 sides so it definitely is behaving exactly as it should.
