### ISSUE TITLE
Use more than 2 UV channels - how?

### ISSUE THREAD

**Issue by RaceTheMaSe** [Koderz/UE4RuntimeMeshComponent#33]
I am quite new to procedural meshes and thanks to your RuntimeMesh I am able to get geometry into Unreal without any problems. So big thanks for your efforts.

Now in need to get a third UV channel to use in the shader material to correctly use the underlying texture atlas.

How can this be acompilshed? Because the APIs are for either one or two UV channels and only in internal structures there are occurences of more UV channels. Would be nice, to give me some directions where to look at.

Cheers Max

**Comment by RaceTheMaSe** [comment]
Some further info after digging deeper:
I am trying to use a FRuntimeMeshVertex<true, true, true, true, 3> VertexWithThreeUvs; directly resulting in an error: error C2039: "TypeInfo" missing

Also tried adding a DEFINE_RUNTIME_MESH_VERTEX(FRuntimeMeshVertexTripleUV);  and DECLARE_INTERAL(...) which results in a crash.

**Comment by Koderz** [comment]
It's been a while since I've tried it and the macros have changed a bit since then and you're also the first to ask about using more than 2 but... 

You should be able to do it via a combination of something like.. 
DECLARE_RUNTIME_MESH_VERTEX(FRuntimeMeshVertexTripleUV, true, true, true, true, 3, ERuntimeMeshVertexTangentBasisType::Default, ERuntimeMeshVertexUVType::HighPrecision)

and 

DEFINE_RUNTIME_MESH_VERTEX(FRuntimeMeshVertexTripleUV);

if that doesn't work let me know. I'm not able to test that right this second.

**Comment by RaceTheMaSe** [comment]
Thats how I declared it, and this crashes the engine in RHI somewhere with errors about NaN in matrix transforms. (not at my PC right now, to be more precise). Don't know what is happening there, as in the initial material I use it doesn't take the additional UV channel into account at all.

Btw: I really like the well engineered code you produced! :-)

**Comment by RaceTheMaSe** [comment]
All Good, the template with three UVs works! :)
